#############################################################################
# >---< This plugin is made by @SkelicStylz and all credits go to him >---< #
#          _____                    _____                    _____          #
#         /\    \                  /\    \                  /\    \         #
#        /::\    \                /::\____\                /::\    \        #
#       /::::\    \              /:::/    /               /::::\    \       #
#      /::::::\    \            /:::/    /               /::::::\    \      #
#     /:::/\:::\    \          /:::/    /               /:::/\:::\    \     #
#    /:::/  \:::\    \        /:::/____/               /:::/__\:::\    \    #
#   /:::/    \:::\    \      /::::\    \              /::::\   \:::\    \   #
#  /:::/    / \:::\    \    /::::::\    \   _____    /::::::\   \:::\    \  #
# /:::/    /   \:::\ ___\  /:::/\:::\    \ /\    \  /:::/\:::\   \:::\    \ #
#/:::/____/  ___\:::|    |/:::/  \:::\    /::\____\/:::/__\:::\   \:::\____\#
#\:::\    \ /\  /:::|____|\::/    \:::\  /:::/    /\:::\   \:::\   \::/    /#
# \:::\    /::\ \::/    /  \/____/ \:::\/:::/    /  \:::\   \:::\   \/____/ #
#  \:::\   \:::\ \/____/            \::::::/    /    \:::\   \:::\    \     #
#   \:::\   \:::\____\               \::::/    /      \:::\   \:::\____\    #
#    \:::\  /:::/    /               /:::/    /        \:::\   \::/    /    #
#     \:::\/:::/    /               /:::/    /          \:::\   \/____/     #
#      \::::::/    /               /:::/    /            \:::\    \         #
#       \::::/    /               /:::/    /              \:::\____\        #
#        \::/____/                \::/    /                \::/    /        #
#                                  \/____/                  \/____/         #                                                                        
# >---------------------< © 2018 GewoonHDEnterprise >---------------------< #
#############################################################################

# This config lets you change if some drugs are addictive or not and lets you change after how many times you use it its addictive
# This is the name of the drug, You can't change the anme of it!
cocaïne:
  # if this is set to true then when you use it you have a change to get addicted to it.
  addictive: true 
  # this is after how many times you can get addicted to it.
  after_how_many_times: 1
weed:
  addictive: true
  after_how_many_times: 5