main: nl.skelic.drugs.Main
name: GHGDrugsRemastered
version: 1.4
author: SkelicStylz
description: GHGDrugs Remastered Let you use Drugs in Minecraft (Don't do Drugs in RealLife).
commands:
  dshop:
    description: This opens the Drugs Shop
    usage: /dshop
    permission: ghgdrugs.dshop
    permission-message: Sorry you don't have permissions to preform that command!
  reborn:
    description: If you don't wanne be a druggie anymore then you can rebirth!
    usage: /reborn
    permission: ghgdrugs.reborn
    permission-message: Sorry you don't have permissions to preform that command!